### ISSUE TITLE
128GB RAM but build mentions only 64GB

### ISSUE THREAD

**Issue by likewise** [eriksjolund/PC-build-128Gb-X570-AMD-Ryzen-9-3900x#2]
Hello,

I was searching how to support 128GB with Ryzen 3900x, because many motherboards do not support 4 slots at high DDR speed, only 2 slots.

In your title is says 128GB but in your build I think you mention 2x32GB = 64 GB.

Can you please elaborate this?

**Comment by eriksjolund** [comment]
The column _Count_ has the value _2_.
In other words two of these
https://www.corsair.com/us/en/Categories/Products/Memory/VENGEANCE-LPX/p/CMK64GX4M2E3200C16

Total RAM is = 2 * 2 * 32 GB = 128 GB

**Comment by eriksjolund** [comment]
I don't have access to the computer right now so I can't check the DDR speed, but I remember that

`cat /proc/meminfo | grep MemTotal`

showed that it had 128 GB.

**Comment by likewise** [comment]
Thank you.  If I am not mistaken, ASUS does not mention a QVL for 128GB in 4x32GB configuration:

https://dlcdnets.asus.com/pub/ASUS/mb/SocketAM4/TUF_GAMING_X570-PLUS/Memory_QVL_3rd_Gen_AMD_Ryzen_Processors_X570_0722.pdf

This is the reason I chose for i7-10700K + 4x32GB DDR4-3600 for one of my builds, whereas my preference was slightly for 3900x. (Although my main application is single-threaded).

Thanks for sharing your build.
